### ISSUE TITLE
Error depending on location of rmirro: OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by fkoenigde** [hersle/rmirro#7]
So first of all I found a way to effectively call on rmirro.py in Windows 10 after installing Windows Subsystem for Linux, which leads me through the process effectively and which is working fine using the path I specified. This way I only have to click the .bat file and enter the root-user password and the passphrase of the key at the start of the process.
1.) using a `.bat` file with the content of
```
wsl.exe su
root @pause
```
2. adding the following lines to the `.bashhrc` file in /root/
```
if [ -z "$SSH_AUTH_SOCK" ] ; then
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
cd /mnt/c/Users/'User/Desktop/RMIRRO/
python3 rmirro.py
fi
```

When I try using another location "/mnt/a/Termine/Template/RMIRRO/", the one I actually intend to use it for, I get an error message, which I don't understand after it successfully creates the `remarkable_backup` (all the data are there) and the `remarkable_metadata` (all the data are there) folder. The folder `remarkable` ist created but apart from one folder and one file it is empty: 

```Pull 71, push 0 and drop 0 files, rendering with render_usb.py (y/n)? y
! (1/71) PULL: 20240411_Donnerstag
! (2/71) PULL: 20240411_Donnerstag/24_EXXXXXX.pdf
Traceback (most recent call last):
  File "/mnt/a/Termine/Template/RMIRRO/rmirro.py", line 545, in <module>
    rm_file.download()
  File "/mnt/a/Termine/Template/RMIRRO/rmirro.py", line 323, in download
    os.utime(outfile, (atime, mtime))
OSError: [Errno 22] Invalid argument
```

I already tried `chmod 777 /mnt/a/Termine/Template/RMIRRO/` as I suspected it might about user rights. Additional Infos: Volume A is a mounted Veracrypt Volume, which FAT32 formatted. Are there any restrictions to the `os.utime` function?

Any ideas on how to fix this or how build checks for after the point of failure?

**Comment by fkoenigde** [comment]
Never Mind. I created a Veracrypt NTFS Volume, which didn't produce the error. Seems like another requirement that the volume is formatted in a specific way (again a chat GPT suggestion). It seems to be working for NTFS and probably EXT4 as you are using Linux. I asked Chat GPT for file systems which might be supported. Probably important to add this to requirements.

```
Apart from NTFS, several other modern file systems support setting file attributes and storing timestamps programmatically. Some of these file systems include:

ext4: The default file system for many Linux distributions, ext4 supports setting access and modification times as well as various file attributes such as permissions, ownership, and extended attributes.

HFS+ (Mac OS Extended): Used by macOS, HFS+ supports file attributes and timestamps, including access time, modification time, and creation time.

APFS (Apple File System): The successor to HFS+, APFS is the default file system for macOS High Sierra and later versions. It supports various file attributes and timestamps.

exFAT (Extended File Allocation Table): Developed by Microsoft, exFAT is designed to be a lightweight file system optimized for flash drives and other removable storage devices. It supports file timestamps and attributes.

XFS (XFS File System): Used primarily on Linux systems, XFS supports setting file attributes and timestamps. It is known for its high performance and scalability, particularly for large file systems.

Btrfs (B-tree File System): Another modern file system for Linux, Btrfs supports features such as snapshots, checksums, and compression, along with file attributes and timestamps.

These are just a few examples of file systems that support setting file attributes and timestamps programmatically. Each file system may have its own set of features and limitations, so it's important to choose the appropriate file system based on your specific requirements and use case.
```
